Allow running the tests with an API key
Why is this change needed?
--------------------------
This is helpful to test options that regular users have access to,
instead of the more limited options available to the YOUR_API_KEY_HERE
user.

How does it address the issue?
------------------------------
If we can find a key in the file tmp/.docraptor_key, we'll rerun the
test with that key set in the environment. In either case we'll run the
test without the key.

Any links to any relevant tickets, articles, or other resources?
---------------------------------------------------------------
https://3.basecamp.com/3093825/buckets/29007795/todolists/5257298552

Did you complete all of the following?
--------------------------------------
- Run test suite?
- Add new tests?
- Consider security implications and practices?

diff --git a/script/inside_container/test b/script/inside_container/test
--- a/script/inside_container/test
+++ b/script/inside_container/test
@@ -24,9 +24,19 @@ fi
 
 cd test
 
+key_relative_path="tmp/.docraptor_key"
+key_path="../$key_relative_path"
+
 # runs a test file with PASS/FAIL message
 run_test() {
-  ruby $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
+  test_name="$1"
+  if [[ "$DOCRAPTOR_KEY" == "" ]] && [ -f "$key_path" ]; then
+    (export DOCRAPTOR_KEY="$(cat "$key_path")" && run_test $1)
+    test_name="$test_name (without "$key_relative_path")"
+  else
+    test_name="$test_name (with "$key_relative_path")"
+  fi
+  ruby $1 && echo "PASS $test_name" || (echo "FAIL $test_name"; exit 1)
 }
 
 if [ "$1" == "" ]; then
