Handle `docker pull` network issues
Why is this change needed?
--------------------------
If `docker pull` can't contact the registry for some reason you can get
an error. This doesn't need to break things if you already have some
version of the container image.

How does it address the issue?
------------------------------
Perform the pull separately, and don't error if it fails. This will
update container images like `mono:latest` so we can easily keep track
of whether or not the latest images fail, but it won't stop the test
process if there are temporary connection issues to the registry.

Usually you'll have a previous version of a container image stored
locally, and that'll be used by `docker run`.

We print a message in case you *really* want to run against the latest
image.

Any links to any relevant tickets, articles, or other resources?
---------------------------------------------------------------

Any screenshots?
----------------

Did you complete all of the following?
--------------------------------------
- Run test suite?
- Add new tests?
- Consider security implications and practices?

diff --git a/script/docker b/script/docker
--- a/script/docker
+++ b/script/docker
@@ -24,13 +24,20 @@ if [[ "$image" == "" ]]; then
   echo "docker image (-i) unset, defaulting to: $image"
 fi
 
+if ! docker pull "$image"; then
+  echo "Pulling the latest version of ${image} failed, but we'll continue in"
+  echo "the hopes that there's a previous version of the container available."
+  echo "This probably isn't an issue unless you really want to verify"
+  echo "everything works with a :latest container image."
+fi
+
 command="$1"
 
 cache_dir="$(pwd)/tmp/cache_${image}"
 mkdir -p "$cache_dir"
 
 set -x
-docker run --pull=always -it --rm \
+docker run -it --rm \
   --env-file .docker_env.list \
   --env RUNTIME_ENV="${image}" \
   --volume /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock \
