New generate_language command.

diff --git a/script/generate_language b/script/generate_language
--- a/script/generate_language
+++ b/script/generate_language
@@ -5,6 +5,11 @@ cd "`dirname \"$0\"`/.."
 LANGUAGE="$1"
 CONFIG_FILE="swagger-config.json"
 
+if [ "$LANGUAGE" == "" ]; then
+  ./script/swagger # prints languages
+  exit 1
+fi
+
 if [ ! -f "$CONFIG_FILE" ]; then
   echo "Could not find $CONFIG_FILE"
   ./script/swagger config-help -l $LANGUAGE
@@ -17,3 +22,8 @@ fi
   -i docraptor.yaml \
   -l $LANGUAGE \
   -c $CONFIG_FILE
+
+# call a generator cleanup script
+if [ -f "script/post_generate_language" ]; then
+  ./script/post_generate_language
+fi
