Add support for hosted docs Increment version to 1.4.0
Why is this change needed?
--------------------------
Hosted docs require new paths and operations in the API.

How does it address the issue?
------------------------------
The latest version of the main swagger config includes the changes necessary.

Any links to any relevant tickets, articles or other resources?
---------------------------------------------------------------

diff --git a/script/swagger b/script/swagger
--- a/script/swagger
+++ b/script/swagger
@@ -8,6 +8,11 @@ if [ "$SWAGGER_CODGEN_REVISION" = "" ]; then
   exit 1
 fi
 
+if ! [ -x "$(command -v mvn)" ]; then
+  echo 'Error: mvn not installed, using homebrew to install' >&2
+  brew install maven
+fi
+
 if [ ! -d "swagger-codegen" ]; then
   git clone https://github.com/swagger-api/swagger-codegen
 fi
