Quiet test run and make passing tests more obvious.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -2,13 +2,18 @@
 set -e
 cd "`dirname \"$0\"`/.."
 
-cd test/
+cd test
 bundle install
+
+# runs a test file with PASS/FAIL message
+run_test() {
+  ruby $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
+}
 
 if [ "$1" == "" ]; then
   for test in $(ls *.rb); do
-    ruby $test
+    run_test $test
   done
 else
-  ruby $1.rb
+  run_test $1.rb
 fi
